name: "Multi event pipeline / workflow"

on: 
  push:
    branches:
      - main
      - Test
        
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: "Check branch and print message"
        run: |
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            echo "This is MAIN branch push"
          elif [[ "$GITHUB_REF" == "refs/heads/Test" ]]; then
            echo "This is TEST branch push"
          else
            echo "Unknown branch"
          fi
